var CENTRAL_ROTA = [
  {date:'07-Dec-2025',time:'8:45am',note:'Communion',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Tim Gosden',r:'Bass player'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Joshua South',r:'Drummer',tbc:true},
    {n:'Paul Swanborough',r:'Keyboard Player'},
  ]},
  {date:'14-Dec-2025',time:'8:45am',note:'Nativity service',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Joshua South',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'14-Dec-2025',time:'6:00pm',note:'Carol service',band:'',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Instrumentalist, Vocalist'},
  ]},
  {date:'21-Dec-2025',time:'8:45am',note:'Christingle',band:'Band 1',members:[
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tom Day',r:'Bass player',tbc:true},
    {n:'Phil Heald',r:'Drummer'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'28-Dec-2025',time:'8:45am',note:'No service',band:'',members:[]},
  {date:'04-Jan-2026',time:'8:45am',note:'Communion',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Tim Gosden',r:'Bass player'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'11-Jan-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Joshua South',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Susanna South',r:'Vocalist'},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'18-Jan-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tom Day',r:'Bass player'},
    {n:'Phil Heald',r:'Drummer'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'25-Jan-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
  ]},
  {date:'01-Feb-2026',time:'8:45am',note:'Communion',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'08-Feb-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Joshua South',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Susanna South',r:'Vocalist'},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'15-Feb-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tom Day',r:'Bass player'},
    {n:'Phil Heald',r:'Drummer'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'22-Feb-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
  ]},
  {date:'01-Mar-2026',time:'8:45am',note:'',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'08-Mar-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Joshua South',r:'Drummer'},
    {n:'Susanna South',r:''},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'15-Mar-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'22-Mar-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
  ]},
  {date:'29-Mar-2026',time:'8:45am',note:'Communion',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Jo Yallop',r:'Keyboard Player, Vocalist'},
  ]},
  {date:'05-Apr-2026',time:'8:45am',note:'Easter Sunday — baptisms',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tom Day',r:'Bass player, Guitarist'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'12-Apr-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Phil Heald',r:'Drummer'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player'},
    {n:'Martha Williams',r:'Vocalist'},
  ]},
  {date:'19-Apr-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer'},
  ]},
  {date:'26-Apr-2026',time:'8:45am',note:'',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'03-May-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Charis Noakes',r:'Guitarist'},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'10-May-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Phil Heald',r:'Drummer'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Martha Williams',r:'Vocalist'},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'17-May-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
  ]},
  {date:'24-May-2026',time:'8:45am',note:'',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'31-May-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tom Day',r:'Bass player, Guitarist'},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'07-Jun-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Phil Heald',r:'Drummer'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Martha Williams',r:'Vocalist'},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'14-Jun-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Paul Swanborough',r:'Keyboard Player'},
  ]},
  {date:'21-Jun-2026',time:'8:45am',note:'',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'28-Jun-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tom Day',r:'Bass player, Guitarist'},
    {n:'Tim Page',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer',clash:true},
  ]},
  {date:'05-Jul-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Phil Heald',r:'Bass player'},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Martha Williams',r:'Vocalist, Worship Leader',wl:true},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'12-Jul-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
  ]},
  {date:'19-Jul-2026',time:'8:45am',note:'',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'26-Jul-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tom Day',r:'Bass player, Guitarist'},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer'},
  ]},
  {date:'02-Aug-2026',time:'8:45am',note:'',band:'Band 1',members:[
    {n:'Phil Heald',r:'Drummer',tbc:true},
    {n:'Charis Noakes',r:'Guitarist, Vocalist, Worship Leader',wl:true,tbc:true},
    {n:'Martha Williams',r:'Vocalist'},
    {n:'Jo Yallop',r:'Keyboard Player'},
  ]},
  {date:'09-Aug-2026',time:'8:45am',note:'',band:'Band 2',members:[
    {n:'Mark Austin',r:'Bass player'},
    {n:'Josie Baker',r:'Vocalist'},
    {n:'Tim Gosden',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Tim Page',r:'Keyboard Player'},
  ]},
  {date:'16-Aug-2026',time:'8:45am',note:'',band:'Band 3',members:[
    {n:'Estera Girdzeviciute',r:'Vocalist'},
    {n:'Pete McAllen',r:'Guitarist, Vocalist, Worship Leader',wl:true},
    {n:'Becky Tidd',r:'Keyboard Player, Vocalist, Worship Leader',wl:true},
  ]},
  {date:'23-Aug-2026',time:'8:45am',note:'',band:'Band 4',members:[
    {n:'Josie Baker',r:'Vocalist, Worship Leader',wl:true},
    {n:'Tom Day',r:'Bass player, Guitarist',tbc:true},
    {n:'Paul Swanborough',r:'Keyboard Player'},
    {n:'Rick Yallop',r:'Drummer'},
  ]},
  {date:'30-Aug-2026',time:'8:45am',note:'No service — bank holiday',band:'',members:[]},
];

renderRota('rota-central', CENTRAL_ROTA, { scroll: true });
