var CHAPEL_ROTA = [
  {date:'07-Dec-2025',time:'9:00am',note:'Party!',band:'',members:[
    {n:'Sam Consterdine',r:'Vocalist, Guitarist'},
    {n:'James Cornwell',r:'Bass player'},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Claire Knight',r:'Vocalist'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Jo Robertson',r:'Percussion / Cajon'},
  ]},
  {date:'14-Dec-2025',time:'9:00am',note:'Nativity',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'James Cornwell',r:'Bass player'},
    {n:'Joel Graham',r:'Vocalist, Keyboard Player',clash:true},
  ]},
  {date:'21-Dec-2025',time:'9:00am',note:'Christingle',band:'',members:[
    {n:'Phil Jones',r:'Bass player'},
    {n:'Claire Knight',r:'Vocalist'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true,clash:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'28-Dec-2025',time:'9:00am',note:'No service',band:'',members:[]},
  {date:'04-Jan-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Irene Struthers',r:'Keyboard Player'},
  ]},
  {date:'11-Jan-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'18-Jan-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player',clash:true},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'25-Jan-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Steve Hughes',r:'Bass player'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'01-Feb-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'08-Feb-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Irene Struthers',r:'Keyboard Player'},
  ]},
  {date:'15-Feb-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'James Cornwell',r:'Bass player',clash:true},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'22-Feb-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Phil Jones',r:'Bass player'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'01-Mar-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'08-Mar-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'15-Mar-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Irene Struthers',r:'Vocalist, Keyboard Player'},
  ]},
  {date:'22-Mar-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Steve Hughes',r:'Bass player'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'29-Mar-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'05-Apr-2026',time:'9:00am',note:'Easter Sunday',band:'',members:[
    {n:'Phil Jones',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'12-Apr-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player',clash:true},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'19-Apr-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Steve Hughes',r:'Bass player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'26-Apr-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true,clash:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'03-May-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'10-May-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'James Cornwell',r:'Bass player',clash:true},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'17-May-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Steve Hughes',r:'Bass player'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'24-May-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Irene Struthers',r:'Keyboard Player'},
  ]},
  {date:'31-May-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'07-Jun-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'14-Jun-2026',time:'9:00am',note:'Not yet confirmed',band:'',members:[]},
  {date:'21-Jun-2026',time:'9:00am',note:"Father's Day — Communion",band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Irene Struthers',r:'Keyboard Player'},
  ]},
  {date:'28-Jun-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Joel Graham',r:'Worship Leader, Vocalist, Keyboard Player',wl:true,clash:true},
    {n:'Phil Jones',r:'Guitarist'},
    {n:'Claire Knight',r:'Vocalist'},
  ]},
  {date:'05-Jul-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist',clash:true},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
  {date:'12-Jul-2026',time:'9:00am',note:'Communion',band:'',members:[
    {n:'Steve Hughes',r:'Bass player'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
    {n:'Irene Struthers',r:'Vocalist'},
  ]},
  {date:'19-Jul-2026',time:'9:00am',note:'',band:'',members:[
    {n:'Sam Consterdine',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Phil Jones',r:'Bass player'},
    {n:'Letetia Meyer',r:'Instrumentalist'},
    {n:'Irene Struthers',r:'Keyboard Player'},
  ]},
  {date:'26-Jul-2026',time:'9:00am',note:'',band:'',members:[
    {n:'James Cornwell',r:'Bass player'},
    {n:'Jo Robertson',r:'Instrumentalist'},
    {n:'Andrew Southgate',r:'Worship Leader, Vocalist, Guitarist',wl:true},
    {n:'Ruth Southgate',r:'Keyboard Player'},
  ]},
];

renderRota('rota-chapel', CHAPEL_ROTA);
